### ISSUE TITLE
Update against latest dhall-kubernetes release

### ISSUE THREAD

**Issue by PierreR** [TristanCacqueray/dhall-openshift#1]
Hi,

Thanks your for `dhall-openshift`.

I believe some recent changes on `dhall-kubernetes` might have non trivial impact on the end user of `dhall-openshift`. In particular,  I believe this change is quite relevant:
https://github.com/dhall-lang/dhall-kubernetes/commit/381306bcc3fd87aafe042c23bb66fe58227b85f4

Do you intend to update again the latest release of `dhall-kubernetes` in a near future or do you expect users to do it by re-generating `dhall-openshift ?

Cheers

**Comment by TristanCacqueray** [comment]
Hi, yes sure I'll push a branch with the rebuild.

**Comment by TristanCacqueray** [comment]
Actually it seems like using latest dhall-kubernetes binding generator with the [openshift openapi definitions](https://github.com/openshift/origin/blob/master/api/swagger-spec/openshift-openapi-spec.json) results in odd types, for example RouteStatus attribute is now required: https://github.com/TristanCacqueray/dhall-openshift/commit/1901e20eebdcce60e1ca48a8f89d6edf3631cf6b .

Looking at the openshift openapi, it seems like expected, thus we could either patch the generator to make those optional, or we should find a better openapi definition.
Alternatively we could juste update the `io.k8s` types.

What would you prefer @PierreR ?

**Comment by PierreR** [comment]
Is there a better openapi definition somewhere ?

If there is I guess it would be ideal. Otherwise patching is probably better (unless it gets to tiresome in the long run) but if you just update the `io.k8s` that's fine by me.

In the short term, what I would like to do is to use the `dhall-to-yaml` without the `--omit-empty`. I am not using a lot of specific openshift resources a part from `route`, `project` and possibly ` deploymentConfig`.

Thanks for the quick response ! I will test the update asap.

**Comment by TristanCacqueray** [comment]
With CRDs it seems like openapi are no longer used/maintained.

It seems like latest dhall-kubernetes generator is producing a better binding, thus I'll patch it to force top-level status attributes to be optional, that should work well for your use-case.

Thank you for the feedback!

**Comment by TristanCacqueray** [comment]
@PierreR It seems like PR #2 should solve the `omit-empty` usage, please let me know if it works for you.

I haven't tried `deploymentConfig`, and I noticed `ProjectSpec` is missing the `projectRequestTemplate`, but perhaps that could be improved in follow-ups.

**Comment by PierreR** [comment]
@TristanCacqueray  works like a charm on my config.

**Comment by TristanCacqueray** [comment]
Alright, I merged the PR and tagged the result as `v0.2.0` (and made before the `v0.1.0`). Please re-open this issue or create a new one if something somehow broke :)

Cheers

**Comment by PierreR** [comment]
Thanks so much !
